# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://marksjin.github.io/
date_format: "ordinal"
title: 宇字集
subtitle: "梦想总是要有的"
description: "靳宇攀的个人博客"
keywords: 宇字集, 靳宇攀, marksjin
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
auto_spacing: true

# ---------------- #
#      Author      #
# ---------------- #
author: 靳宇攀
organization: baidu, Inc.
organization_url: https://www.baidu.com
location: Beijing, China
email: 18810005642@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: marksjin/marksjin.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: marksjin

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: yupan
disqus_username: yupan
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: true
